version: '3'
services:
    majorproject-rest-server:
        image: backend
        build:
            context: majorproject
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        environment:
            MARIADB_HOST: ${MARIADB_HOST}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    majorproject-frontend:
        image: frontend
        build:
            context: FrontEnd
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        restart: always
        stdin_open: true
        depends_on:
            - majorproject-rest-server